version: '3.3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j:/var/lib/neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
volumes:
  neo4j: